// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Authorization.proto

/*
Package Authentication_Service is a generated protocol buffer package.

It is generated from these files:
	Authorization.proto

It has these top-level messages:
	SingInRequest
	SingInResponse
	SingOutRequest
	SingOutResponse
*/
package Authentication_Service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import Authentication_Service1 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// SingInRequest represents a request to signIn into the system.
type SingInRequest struct {
	Option *Authentication_Service1.RequestOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
	Email  string                                 `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Token  string                                 `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *SingInRequest) Reset()                    { *m = SingInRequest{} }
func (m *SingInRequest) String() string            { return proto.CompactTextString(m) }
func (*SingInRequest) ProtoMessage()               {}
func (*SingInRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SingInRequest) GetOption() *Authentication_Service1.RequestOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *SingInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SingInRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//
// SingInResponse represents response about sign in into the system.
type SingInResponse struct {
	Option *Authentication_Service1.ResponseOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
}

func (m *SingInResponse) Reset()                    { *m = SingInResponse{} }
func (m *SingInResponse) String() string            { return proto.CompactTextString(m) }
func (*SingInResponse) ProtoMessage()               {}
func (*SingInResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SingInResponse) GetOption() *Authentication_Service1.ResponseOption {
	if m != nil {
		return m.Option
	}
	return nil
}

//
// SingOutRequest represents a request to signOut from the system.
type SingOutRequest struct {
	Option *Authentication_Service1.RequestOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
	Email  string                                 `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Token  string                                 `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *SingOutRequest) Reset()                    { *m = SingOutRequest{} }
func (m *SingOutRequest) String() string            { return proto.CompactTextString(m) }
func (*SingOutRequest) ProtoMessage()               {}
func (*SingOutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SingOutRequest) GetOption() *Authentication_Service1.RequestOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *SingOutRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SingOutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//
// SingOutResponse represents response about sign out from the system.
type SingOutResponse struct {
	Option *Authentication_Service1.ResponseOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
}

func (m *SingOutResponse) Reset()                    { *m = SingOutResponse{} }
func (m *SingOutResponse) String() string            { return proto.CompactTextString(m) }
func (*SingOutResponse) ProtoMessage()               {}
func (*SingOutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SingOutResponse) GetOption() *Authentication_Service1.ResponseOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func init() {
	proto.RegisterType((*SingInRequest)(nil), "Authentication.Service.SingInRequest")
	proto.RegisterType((*SingInResponse)(nil), "Authentication.Service.SingInResponse")
	proto.RegisterType((*SingOutRequest)(nil), "Authentication.Service.SingOutRequest")
	proto.RegisterType((*SingOutResponse)(nil), "Authentication.Service.SingOutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Authorization service

type AuthorizationClient interface {
	SignIn(ctx context.Context, in *SingInRequest, opts ...grpc.CallOption) (*SingInResponse, error)
	SingOut(ctx context.Context, in *SingOutRequest, opts ...grpc.CallOption) (*SingOutResponse, error)
}

type authorizationClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationClient(cc *grpc.ClientConn) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) SignIn(ctx context.Context, in *SingInRequest, opts ...grpc.CallOption) (*SingInResponse, error) {
	out := new(SingInResponse)
	err := grpc.Invoke(ctx, "/Authentication.Service.Authorization/SignIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) SingOut(ctx context.Context, in *SingOutRequest, opts ...grpc.CallOption) (*SingOutResponse, error) {
	out := new(SingOutResponse)
	err := grpc.Invoke(ctx, "/Authentication.Service.Authorization/SingOut", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Authorization service

type AuthorizationServer interface {
	SignIn(context.Context, *SingInRequest) (*SingInResponse, error)
	SingOut(context.Context, *SingOutRequest) (*SingOutResponse, error)
}

func RegisterAuthorizationServer(s *grpc.Server, srv AuthorizationServer) {
	s.RegisterService(&_Authorization_serviceDesc, srv)
}

func _Authorization_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authentication.Service.Authorization/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).SignIn(ctx, req.(*SingInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_SingOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).SingOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authentication.Service.Authorization/SingOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).SingOut(ctx, req.(*SingOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authorization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Authentication.Service.Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _Authorization_SignIn_Handler,
		},
		{
			MethodName: "SingOut",
			Handler:    _Authorization_SingOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Authorization.proto",
}

func init() { proto.RegisterFile("Authorization.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x76, 0x2c, 0x2d, 0xc9,
	0xc8, 0x2f, 0xca, 0xac, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x03, 0x09, 0xa6, 0xe6, 0x95, 0x64, 0x26, 0x43, 0x44, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93,
	0x53, 0xa5, 0xb8, 0x9c, 0x12, 0x8b, 0x53, 0x21, 0x6a, 0x94, 0xaa, 0xb8, 0x78, 0x83, 0x33, 0xf3,
	0xd2, 0x3d, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x6c, 0xb9, 0xd8, 0xf2, 0x0b,
	0x40, 0xca, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x54, 0xf5, 0xb0, 0x9b, 0xa2, 0x07, 0xd5,
	0xe0, 0x0f, 0x56, 0x1c, 0x04, 0xd5, 0x24, 0x24, 0xc2, 0xc5, 0x9a, 0x9a, 0x9b, 0x98, 0x99, 0x23,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x80, 0x44, 0x4b, 0xf2, 0xb3, 0x53, 0xf3, 0x24,
	0x98, 0x21, 0xa2, 0x60, 0x8e, 0x52, 0x00, 0x17, 0x1f, 0xcc, 0xee, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x21, 0x3b, 0x34, 0xcb, 0xd5, 0x70, 0x5b, 0x0e, 0xd1, 0x81, 0x6a, 0xbb, 0x52, 0x35, 0xc4,
	0x44, 0xff, 0xd2, 0x92, 0x01, 0xf0, 0x4e, 0x20, 0x17, 0x3f, 0xdc, 0x72, 0xea, 0xf8, 0xc7, 0xe8,
	0x04, 0x23, 0x17, 0x2f, 0x4a, 0xcc, 0x0a, 0x45, 0x72, 0xb1, 0x05, 0x67, 0xa6, 0xe7, 0x79, 0xe6,
	0x09, 0xe1, 0xf4, 0x09, 0x4a, 0x7c, 0x4a, 0xa9, 0x11, 0x52, 0x06, 0xb1, 0x58, 0x89, 0x41, 0x28,
	0x86, 0x8b, 0x1d, 0xea, 0x7e, 0x21, 0xbc, 0x9a, 0x10, 0xa1, 0x2b, 0xa5, 0x4e, 0x50, 0x1d, 0xcc,
	0xf4, 0x24, 0x36, 0x70, 0x7a, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x30, 0x61, 0xe1, 0xce,
	0xaa, 0x02, 0x00, 0x00,
}
