// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Registration.proto

/*
Package Authentication_Service is a generated protocol buffer package.

It is generated from these files:
	Registration.proto

It has these top-level messages:
	RegisterUserRequest
	RegisterUserResponse
	UnRegisterUserRequest
	UnRegisterUserResponse
*/
package Authentication_Service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import Authentication_Service1 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// RegisterUserRequest represents a request to create new user account.
type RegisterUserRequest struct {
	Option   *Authentication_Service1.RequestOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
	Email    string                                 `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string                                 `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterUserRequest) Reset()                    { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()               {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterUserRequest) GetOption() *Authentication_Service1.RequestOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//
// RegisterUserResponse represents response about user create account with
// asymmetrical ciphering token.
type RegisterUserResponse struct {
	Option *Authentication_Service1.ResponseOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
	Token  string                                  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *RegisterUserResponse) Reset()                    { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()               {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterUserResponse) GetOption() *Authentication_Service1.ResponseOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *RegisterUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//
// UnRegisterUserRequest represents a request to disable user account.
type UnRegisterUserRequest struct {
	Option   *Authentication_Service1.RequestOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
	Email    string                                 `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string                                 `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *UnRegisterUserRequest) Reset()                    { *m = UnRegisterUserRequest{} }
func (m *UnRegisterUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UnRegisterUserRequest) ProtoMessage()               {}
func (*UnRegisterUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UnRegisterUserRequest) GetOption() *Authentication_Service1.RequestOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *UnRegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UnRegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//
// UnRegisterUserResponse represents response about disabling user account.
type UnRegisterUserResponse struct {
	Option *Authentication_Service1.ResponseOption `protobuf:"bytes,1,opt,name=option" json:"option,omitempty"`
}

func (m *UnRegisterUserResponse) Reset()                    { *m = UnRegisterUserResponse{} }
func (m *UnRegisterUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UnRegisterUserResponse) ProtoMessage()               {}
func (*UnRegisterUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UnRegisterUserResponse) GetOption() *Authentication_Service1.ResponseOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "Authentication.Service.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "Authentication.Service.RegisterUserResponse")
	proto.RegisterType((*UnRegisterUserRequest)(nil), "Authentication.Service.UnRegisterUserRequest")
	proto.RegisterType((*UnRegisterUserResponse)(nil), "Authentication.Service.UnRegisterUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RegisterUser service

type RegisterUserClient interface {
	Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	UnRegister(ctx context.Context, in *UnRegisterUserRequest, opts ...grpc.CallOption) (*UnRegisterUserResponse, error)
}

type registerUserClient struct {
	cc *grpc.ClientConn
}

func NewRegisterUserClient(cc *grpc.ClientConn) RegisterUserClient {
	return &registerUserClient{cc}
}

func (c *registerUserClient) Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := grpc.Invoke(ctx, "/Authentication.Service.RegisterUser/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerUserClient) UnRegister(ctx context.Context, in *UnRegisterUserRequest, opts ...grpc.CallOption) (*UnRegisterUserResponse, error) {
	out := new(UnRegisterUserResponse)
	err := grpc.Invoke(ctx, "/Authentication.Service.RegisterUser/UnRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RegisterUser service

type RegisterUserServer interface {
	Register(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	UnRegister(context.Context, *UnRegisterUserRequest) (*UnRegisterUserResponse, error)
}

func RegisterRegisterUserServer(s *grpc.Server, srv RegisterUserServer) {
	s.RegisterService(&_RegisterUser_serviceDesc, srv)
}

func _RegisterUser_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterUserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authentication.Service.RegisterUser/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterUserServer).Register(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegisterUser_UnRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnRegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterUserServer).UnRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authentication.Service.RegisterUser/UnRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterUserServer).UnRegister(ctx, req.(*UnRegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegisterUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Authentication.Service.RegisterUser",
	HandlerType: (*RegisterUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegisterUser_Register_Handler,
		},
		{
			MethodName: "UnRegister",
			Handler:    _RegisterUser_UnRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Registration.proto",
}

func init() { proto.RegisterFile("Registration.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x29, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12,
	0x73, 0x2c, 0x2d, 0xc9, 0x48, 0xcd, 0x2b, 0xc9, 0x4c, 0x86, 0x88, 0x06, 0xa7, 0x16, 0x95, 0x65,
	0x26, 0xa7, 0x4a, 0x71, 0x39, 0x25, 0x16, 0xa7, 0x42, 0xd4, 0x28, 0xb5, 0x31, 0x72, 0x09, 0x43,
	0xb4, 0xa6, 0x16, 0x85, 0x16, 0xa7, 0x16, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xd9,
	0x72, 0xb1, 0xe5, 0x17, 0x80, 0x74, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xa9, 0xea, 0x61,
	0x37, 0x4c, 0x0f, 0xaa, 0xc1, 0x1f, 0xac, 0x38, 0x08, 0xaa, 0x49, 0x48, 0x84, 0x8b, 0x35, 0x35,
	0x37, 0x31, 0x33, 0x47, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x11, 0x92, 0xe2, 0xe2,
	0x28, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x06, 0x4b, 0xc0, 0xf9, 0x4a, 0x39,
	0x5c, 0x22, 0xa8, 0xee, 0x28, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xb2, 0x43, 0x73, 0x88, 0x1a,
	0x6e, 0x87, 0x40, 0x74, 0x60, 0xba, 0xa4, 0x24, 0x3f, 0x3b, 0x35, 0x0f, 0xe6, 0x12, 0x30, 0x47,
	0xa9, 0x83, 0x91, 0x4b, 0x34, 0x34, 0x6f, 0x50, 0x78, 0x3c, 0x82, 0x4b, 0x0c, 0xdd, 0x25, 0xd4,
	0xf1, 0xba, 0xd1, 0x33, 0x46, 0x2e, 0x1e, 0x64, 0x83, 0x85, 0xd2, 0xb9, 0x38, 0x60, 0x7c, 0x21,
	0x6d, 0xdc, 0x86, 0x61, 0x04, 0x8a, 0x94, 0x0e, 0x71, 0x8a, 0x21, 0xae, 0x50, 0x62, 0x10, 0xca,
	0xe5, 0xe2, 0x42, 0xf8, 0x49, 0x48, 0x17, 0x97, 0x6e, 0xac, 0x31, 0x20, 0xa5, 0x47, 0xac, 0x72,
	0x98, 0x75, 0x49, 0x6c, 0xe0, 0xb4, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x60, 0x41,
	0x78, 0x05, 0x03, 0x00, 0x00,
}
